default:
  image: python:3.12-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .venv

before_script:
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install -e .

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == 'main'

stages:
  - Install
  - Static Analysis
  - Test
  - Ship
  - Documentation

# ------------------------------- Install -------------------------------------

pip_install:
  stage: Install
  before_script:
    - python --version ; pip --version
  script:
    - pip install .
    - pip list -v

# ------------------------------ Static analysis ------------------------------

.static_analysis_base:
  stage: Static Analysis
  allow_failure: true

flake8:
  needs:
    - pip_install
  extends: .static_analysis_base
  script:
    - pip install flake8
    - flake8 --ignore E501 ./dinamis_sdk

pylint:
  needs:
    - pip_install
  extends: .static_analysis_base
  script:
    - pip install pylint
    - pylint ./dinamis_sdk

codespell:
  needs:
    - pip_install
  extends: .static_analysis_base
  script: 
    - pip install codespell
    - codespell ./dinamis_sdk docs README.md

pydocstyle:
  needs:
    - pip_install
  extends: .static_analysis_base
  script:
    - pip install pydocstyle
    - pydocstyle ./dinamis_sdk

mypy:
  needs:
    - pip_install
  extends: .static_analysis_base
  script:
    - pip install mypy
    - pip list -v
    - mypy --install-types --non-interactive .

# --------------------------------- Doc ---------------------------------------

.doc_base:
  stage: Documentation
  before_script:
    - pip install -r doc/doc_requirements.txt
  artifacts:
    paths:
      - public
      - public_test

test:
  extends: .doc_base
  except:
    - main
  script:
    - mkdocs build --site-dir public_test

pages:
  extends: .doc_base
  only:
    - main
  script:
    - mkdocs build --site-dir public

# --------------------------------- Test --------------------------------------

.tests_base:
  needs:
    - pip_install
  stage: Test
  except:
    - main

OAuth2 Tests:
  extends: .tests_base
  script:
    - python tests/test_spot-6-7-drs.py
    - python tests/test_super-s2.py
    - python tests/test_push.py

API key Tests:
  extends: .tests_base
  script:
    - dinamis_cli register
    - mv /root/.config/dinamis_sdk_auth/.token /root/.config/dinamis_sdk_auth/.token_
    - python tests/test_spot-6-7-drs.py
    - python tests/test_super-s2.py
    - python tests/test_push.py
    - mv /root/.config/dinamis_sdk_auth/.token_ /root/.config/dinamis_sdk_auth/.token
    - dinamis_cli delete
    - toto=$(dinamis_cli create 2>&1)
    - mv /root/.config/dinamis_sdk_auth/.token /root/.config/dinamis_sdk_auth/.token_
    - export DINAMIS_SDK_ACCESS_KEY=$(echo $toto | cut -d"'" -f4)
    - export DINAMIS_SDK_SECRET_KEY=$(echo $toto | cut -d"'" -f8)
    - python tests/test_spot-6-7-drs.py
    - mv /root/.config/dinamis_sdk_auth/.token_ /root/.config/dinamis_sdk_auth/.token
    - dinamis_cli revoke $DINAMIS_SDK_ACCESS_KEY

# --------------------------------- Ship --------------------------------------

pypi:
  stage: Ship
  only:
    - main
  script:
    - pip install --upgrade build twine
    - python3 -m build
  after_script:
    - python3 -m twine upload --repository-url https://upload.pypi.org/legacy/ --non-interactive --verbose -u __token__ -p $pypi_token dist/*
