include:
  - project: "cdos-pub/pycode-quality"
    ref: "main"
    file:
      - ".gitlab/ci/static-analysis.yml"
      - ".gitlab/ci/doc.yml"
      - ".gitlab/ci/pip.yml"

variables:
  IMPL_MODULE_NAME: dinamis_sdk

  PYTHON_IMG: python:3.12-slim
  PIP_RASTERIO_USED: true
  PIP_PACKAGE_URL: "https://upload.pypi.org/legacy/"
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: ${pypi_token} 

  DOC_BUILD_SELF: true

stages:
  - Static Analysis
  - Test
  - Documentation
  - Pip

.static_analysis_base:
  allow_failure: false

.tests_base:
  extends: .static_analysis_with_pip_install
  stage: Test

pylint:
  script:
    - pip install pylint
    - pylint dinamis_sdk tests


OAuth2 Tests:
  extends: .tests_base
  script:
    - python tests/test_spot_6_7_drs.py
    - python tests/test_super_s2.py
    - python tests/test_push.py
    - python tests/test_headers.py authorization

API key Tests:
  extends: .tests_base
  script:
    - dinamis_cli register
    - python tests/test_headers.py access-key
    # ensure that we une only API key from now
    - mv /root/.config/dinamis_sdk_auth/.jwt /root/.config/dinamis_sdk_auth/.jwt_
    - python tests/test_spot_6_7_drs.py
    - python tests/test_super_s2.py
    - python tests/test_push.py
    # Test API key from environment variables
    - export DINAMIS_SDK_ACCESS_KEY=$(cat /root/.config/dinamis_sdk_auth/.apikey | cut -d'"' -f4)
    - export DINAMIS_SDK_SECRET_KEY=$(cat /root/.config/dinamis_sdk_auth/.apikey | cut -d'"' -f8)
    - rm /root/.config/dinamis_sdk_auth/.apikey  # ensure that we use env. vars.
    - python tests/test_spot_6_7_drs.py
    # bring back oauth2 credentials so we can revoke the API key
    - mv /root/.config/dinamis_sdk_auth/.jwt_ /root/.config/dinamis_sdk_auth/.jwt
    - dinamis_cli revoke ${DINAMIS_SDK_ACCESS_KEY}
