# mkdocs.yml
theme:
  logo: https://theia.sedoo.fr/wp-content-theia/uploads/sites/6/2020/05/Logo_DINAMIS_300px.png
  name: "material"
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - content.code.annotate
    - toc.follow
    - navigation.instant
    - content.code.copy

plugins:
- search
- gen-files:
    scripts:
    - doc/gen_ref_pages.py
- mkdocstrings:
    watch:
    - dinamis_sdk/
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mermaid2

nav:
- Home: index.md
- Credentials: credentials.md
- Additional resources: additional_resources.md
- Examples:
  - Processing: processing_examples.md
  - QGIS: qgis.md
- API reference:  reference/

# Customization
extra:
  feature:
    tabs: true
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.irstea.fr/dinamis/dinamis-sdk

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      title: On this page
      toc_depth: 1-2
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# rest of the navigation..
site_name: Dinamis-SDK
repo_url: https://gitlab.irstea.fr/dinamis/dinamis-sdk
repo_name: dinamis-sdk
docs_dir: doc/
