# mkdocs.yml
theme:
  logo: https://theia.sedoo.fr/wp-content-theia/uploads/sites/6/2020/05/Logo_DINAMIS_300px.png
  name: "material"
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - content.code.annotate
    - navigation.tabs
    - toc.follow
    
plugins:
- search
- gen-files:
    scripts:
    - doc/gen_ref_pages.py
- mkdocstrings:
    watch:
    - dinamis_sdk/
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mermaid2

nav:
- API:  reference/ 
- Home: index.md

# Customization
extra:
  feature:
    tabs: true
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.irstea.fr/umr-tetis/scenes

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

# rest of the navigation..
site_name: DINAMIS-SDK
repo_url: https://gitlab.irstea.fr/dinamis/dinamis-sdk
repo_name: dinamis-sdk
docs_dir: doc/
